name: Flutter Analyze & Test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.12.13+hotfix.6'
          channel: beta
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
